name: Deploy Laravel Monolith

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl, sqlite

      # 3️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 4️⃣ Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # 5️⃣ Install Node dependencies
      - name: Install Node dependencies
        run: npm ci

      # 6️⃣ Build frontend (Vite)
      - name: Build frontend
        run: composer run dev

      # 7️⃣ Deploy to VPS via SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            echo "🚀 Starting deployment..."
            cd /var/www/your-project
            git pull origin main
            composer install --no-dev --prefer-dist --optimize-autoloader
            npm ci
            composer run dev
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            echo "✅ Deployment finished successfully!"
