name: Deploy Laravel App
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # 2️⃣ Setup PHP & Composer
      - name: Setup PHP and Install Dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl, sqlite3
          tools: composer
      
      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      
      # 3️⃣ Setup Node.js & Build Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install npm dependencies
        run: npm ci
      
      - name: Build frontend
        run: npm run build
      
      # 4️⃣ Deploy files to VPS via rsync
      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_KEY }}
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          TARGET: /var/www/your-project
          SOURCE: ./
          ARGS: "-rlgoDzvc --delete"
          EXCLUDE: "/dist/, /node_modules/, /.git/, /.github/, .env"
          REMOTE_PORT: 22
          SSH_CMD_ARGS: "-o StrictHostKeyChecking=no"
      
      # 5️⃣ Run post-deployment commands on VPS
      - name: Post-deployment Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            cd /var/www/your-project
            composer install --no-dev --prefer-dist --optimize-autoloader
            npm ci
            npm run build
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            # Fix permissions
            sudo chown -R www-data:www-data /var/www/your-project
            sudo chmod -R 755 /var/www/your-project/storage
            sudo chmod -R 755 /var/www/your-project/bootstrap/cache
