name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup PHP & Install Composer dependencies
      - name: Setup PHP and Install Dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl, sqlite3
          tools: composer
      - run: composer install --no-dev --prefer-dist --optimize-autoloader

      # 3️⃣ Setup Node.js, Install, and Build Frontend
      - name: Setup Node and Build Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build

      # 4️⃣ Deploy files to VPS using rsync
      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_KEY }}
          REMOTE_USER: ${{ secrets.VPS_USER }}        # hanya username
          REMOTE_HOST: ${{ secrets.VPS_HOST }}        # hanya IP/domain, jangan ada @ atau port
          TARGET: "/var/www/your-project"
          SOURCE: "./"                                # direktori repo
          ARGS: "-rlgoDzvc --delete"
          EXCLUDE: ".git,.github,node_modules,.env"

      # 5️⃣ Run post-deployment commands on VPS
      - name: Run Post-Deployment Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          script: |
            cd /var/www/your-project
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            # Optional: set permission & restart service
            # sudo chown -R www-data:www-data /var/www/your-project
            # sudo systemctl restart php8.2-fpm
