- name: Deploy to VPS
  uses: appleboy/ssh-action@v0.1.7
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USER }}
    key: ${{ secrets.VPS_KEY }}
    port: 22
    script: |
      cd /var/www/your-project
      git pull origin main
      composer install --no-dev --prefer-dist --optimize-autoloader
      npm ci
      npm run build
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
